Updated labs 191 and 201 - K8S Version 1.20
aws-samples/eks-workshop pull request #1233
Opened 2021-07-30 15:34 UTC by claubota

*Description of changes:*

Updated labs 191 and 201. Tested both on versions 1.19 and 1.20

Lab 191 - Encrypting Secrets with KMS:

- Fixed typos / rephrased sentences
- Updated reasons to use custom key store to match the documentation

Lab 201 - Resource Management:

- Fixed typos / rephrased sentences
- Reordered pod creation to make it easier to follow
- Fixed output rendering error
- Added output for Resource Quotas

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-09-17 15:02 UTC, buzzsurfr requested changes
Small note additional and change but otherwise LGTM

2021-09-17 15:02 UTC, buzzsurfr commented on content/beginner/191_secrets/kms-custom-keystore.md
> +Aside from compliance and security requirements, your may want to consider the cost of using custom key stores. Below you can find a cost comparison between default AWS KMS key store and AWS KMS cust
"your may" -> "you may"

Also add a note that this assumes a certain region and provide a link where they can find the latest KMS pricing information (to https://aws.amazon.com/kms/pricing/).

2021-11-10 16:14 UTC, claubota commented
Fixed typos, added pricing information and updated last review date

2021-11-16 16:59 UTC, buzzsurfr requested changes
One small change, and one additional maintenance action (while reviewing the module), then ready for approval.

2021-11-16 16:59 UTC, buzzsurfr commented on content/intermediate/201_resource_management/basic-pod-limits.md
>  We will create four pods:
This feels out of place with the **Deploy Metrics Server** section. Consider putting metrics server on it's own page as a module prerequisite, or at least moving above deploying the pods.

2021-11-16 16:59 UTC, buzzsurfr commented on content/intermediate/201_resource_management/cleaning.md
>  ---
Please rename the _file_ from `cleaning.md` to `cleanup.md` to match with other modules.

2021-11-17 10:52 UTC, claubota commented
Added a separate page for the Metric Server. Renamed cleaning.md to cleanup.md

2021-11-18 21:39 UTC, buzzsurfr approved these changes
LGTM :shipit:

2021-11-18 21:39 UTC, merged