Update http_data.md
aws-samples/eks-workshop pull request #1436
Opened 2022-06-30 07:59 UTC by krish-kp

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-06-30 09:49 UTC, allamand requested changes

2022-06-30 09:49 UTC, allamand commented on content/intermediate/241_pixie/using_pixie/http_data.md
> +Delete line 29  ```bash df.node = df.ctx['node']``` and replace it with the following.
Seems that bash is display in the result can you fix this ?

2022-06-30 16:19 UTC, krish-kp commented
Updated

2022-07-01 14:40 UTC, allamand approved these changes
LGTM

2022-07-01 14:41 UTC, merged